### ISSUE TITLE
ATM6Sky Server Multiplayer screen issue

### ISSUE THREAD

**Issue by Mycraft1105** [AllTheMods/atm6-sky#121]
I am running an ATM6 Sky server but in the multiplayer menu it says for everyone: "Can't connect to server" but me and all my friends on other locations can join and play just fine. The server icon is also not showing up... Does anyone have an idea how to fix this?
![c89bul41sqp61](https://user-images.githubusercontent.com/55346958/112980486-3cea3c00-915a-11eb-8356-009c17991d3e.png)

I figured out why this happened!
This is because my server icon is causing errors: 
`[09:25:26] [Netty Epoll Server IO #1/ERROR] [minecraft/NettyPacketEncoder]: Error encoding packet
io.netty.handler.codec.EncoderException: String too big (was 37061 bytes encoded, max 32767)
        at net.minecraft.network.PacketBuffer.func_211400_a(PacketBuffer.java:363) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:packetsizelimits.PacketBufferMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:357) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:packetsizelimits.PacketBufferMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.status.server.SServerInfoPacket.func_148840_b(SServerInfoPacket.java:33) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:38) [?:?] {re:classloading}
        at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) [?:?] {re:classloading}
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkManager.func_201058_a(NetworkManager.java:163) [?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:157) [?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.network.status.ServerStatusNetHandler.func_147312_a(SourceFile:42) [?:?] {re:classloading}
        at net.minecraft.network.status.client.CServerQueryPacket.func_148833_a(SourceFile:22) [?:?] {re:classloading}
        at net.minecraft.network.status.client.CServerQueryPacket.func_148833_a(SourceFile:8) [?:?] {re:classloading}
        at net.minecraft.network.NetworkManager.func_197664_a(NetworkManager.java:148) [?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:138) [?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49) [?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94) [?:?] {re:classloading}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server-1.16.5-20210115.111550-extra.jar:?] {}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
`
I get that in the console every time someone clicks refresh, can this be fixed? 
This is my server icon: 
![server-icon](https://user-images.githubusercontent.com/55346958/113106844-8478d280-9203-11eb-8df8-a98b6f3b1cc4.png)

**Comment by oly2o6** [comment]
i am going to close this because i quite franky have no idea why or whats happening as ive seen multiple people use icons perfectly fine, ill still look into it though and let you know if i figure out what your specific issue is
