### ISSUE TITLE
atm6s doesnt start on macos

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [AllTheMods/atm6-sky#139]
**Describe the bug**

The modpack does not start on macOS 11.2.3. using MultiMC.
Playing vanilla and All the mods 6 and other modpacks does work perfectly.

**Additional context**
https://paste.ee/p/71EXU

**Part of the error:**

[19:58:58] [Render thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalStateException: Failed to compile shader:
ERROR: 0:1: '' :  version '130' is not supported
	at imgui.gl3.ImGuiImplGl3.createAndCompileShader(ImGuiImplGl3.java:445) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.createShaders(ImGuiImplGl3.java:298) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.createDeviceObjects(ImGuiImplGl3.java:260) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.init(ImGuiImplGl3.java:123) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.init(ImGuiImplGl3.java:85) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.imgui.Gui.init(Gui.kt:68) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.internal.Listeners$Common$onLoadCComplete$1$1.invoke(Listeners.kt:55) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.internal.Listeners$Common$onLoadCComplete$1$1.invoke(Listeners.kt:47) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.util.UtilsKt$sam$com_mojang_blaze3d_systems_IRenderCall$0.execute(Utils.kt) ~[bpm:1.0.2.65] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:116) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:MainWindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.2-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
[19:58:59] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/1/21, 7:58 PM
Description: Unexpected error

java.lang.IllegalStateException: Failed to compile shader:
ERROR: 0:1: '' :  version '130' is not supported
	at imgui.gl3.ImGuiImplGl3.createAndCompileShader(ImGuiImplGl3.java:445) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.createShaders(ImGuiImplGl3.java:298) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.createDeviceObjects(ImGuiImplGl3.java:260) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.init(ImGuiImplGl3.java:123) ~[bpm:1.0.2.65] {re:classloading}
	at imgui.gl3.ImGuiImplGl3.init(ImGuiImplGl3.java:85) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.imgui.Gui.init(Gui.kt:68) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.internal.Listeners$Common$onLoadCComplete$1$1.invoke(Listeners.kt:55) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.internal.Listeners$Common$onLoadCComplete$1$1.invoke(Listeners.kt:47) ~[bpm:1.0.2.65] {re:classloading}
	at me.jraynor.util.UtilsKt$sam$com_mojang_blaze3d_systems_IRenderCall$0.execute(Utils.kt) ~[bpm:1.0.2.65] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:116) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:MainWindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.2-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

**Comment by jstansel** [comment]
I had a related problem on Linux. The imgui library has native dependencies and my system didn't have the required shared library installed. I am not sure what your exception means but it is from the same library. With MultiMC it is easy to disable or remove the bpm mod and then I was able to load the rest of the pack.

**Comment by Vertigo81** [comment]
The blueprint mod (bpm) doesn't work with Mac atm (or its improperly configured).  If you remove it from the pack it should work (or run a version before 1.0.5 when it was added)

**Comment by twreid** [comment]
> The blueprint mod (bpm) doesn't work with Mac atm (or its improperly configured). If you remove it from the pack it should work (or run a version before 1.0.5 when it was added)

Just wanted to confirm that I disabled this mod in MultiMC and it launched fine after that. Thank you.

**Comment by pdawson** [comment]
I had the same problem on Ubuntu. 

I updated bpm to the latest version (1.0.2.71) and it appears to have been fixed.

**Comment by MathiasDeWeerdt** [comment]
> I had the same problem on Ubuntu.
> 
> I updated bpm to the latest version (1.0.2.71) and it appears to have been fixed.

Newest version doesnt fix it on macOS.
