### ISSUE TITLE
Ensorcellation FrostRebukeEnchantment crashloop

### ISSUE THREAD

**Issue by featherspeed** [AllTheMods/atm6-sky#149]
it looks like the mob farm gets a problem with one of the generated mobs having the enchant

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/4/21 8:50 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.entity.player.ServerPlayerEntity.func_70670_a(ServerPlayerEntity.java:1114) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_195064_c(LivingEntity.java:825) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A}
	at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.onHit(FrostRebukeEnchantment.java:92) ~[?:1.2.0] {re:classloading}
	at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.func_151367_b(FrostRebukeEnchantment.java:72) ~[?:1.2.0] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper.func_212575_b(EnchantmentHelper.java:141) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper$$Lambda$30823/140551451.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.enchantment.EnchantmentHelper.func_222184_a(EnchantmentHelper.java:104) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper$$Lambda$30809/1046275467.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:103) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:113) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:144) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1152) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:balancedenchanting.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1292) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:101) ~[?:1.16.5-0.4.2] {re:classloading}
	at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:66) ~[?:1.16.5-0.4.2] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$29352/303020479.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_70670_a(ServerPlayerEntity.java:1114) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_195064_c(LivingEntity.java:825) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A}
	at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.onHit(FrostRebukeEnchantment.java:92) ~[?:1.2.0] {re:classloading}
	at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.func_151367_b(FrostRebukeEnchantment.java:72) ~[?:1.2.0] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper.func_212575_b(EnchantmentHelper.java:141) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper$$Lambda$30823/140551451.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.enchantment.EnchantmentHelper.func_222184_a(EnchantmentHelper.java:104) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper$$Lambda$30809/1046275467.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:103) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:113) ~[?:?] {re:classloading}
	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:144) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1152) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:balancedenchanting.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1292) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:101) ~[?:1.16.5-0.4.2] {re:classloading}
	at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:66) ~[?:1.16.5-0.4.2] {re:classloading}
-- Block entity being ticked --
Details:
	Name: mob_grinding_utils:saw // mob_grinding_utils.tile.TileEntitySaw
	Block: Block{mob_grinding_utils:saw}[facing=up,powered=true]
	Block location: World: (32,62,16), Chunk: (at 0,3,0 in 2,1; contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{mob_grinding_utils:saw}[facing=up,powered=true]
	Block location: World: (32,62,16), Chunk: (at 0,3,0 in 2,1; contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3099300 game time, 3249885 day time
	Level name: Featherspeed
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 18372 (now: false), thunder time: 144581 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$29352/303020479.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1189877576 bytes (1134 MB) / 3149922304 bytes (3004 MB) up to 5130158080 bytes (4892 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5504m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.2
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.10.0

**Comment by MelanX** [comment]
Please use pastebin or gist or another service to provide crash reports. This looks aweful and is too hard to read.
