### ISSUE TITLE
Chunky turtle in the end causing crash on loading

### ISSUE THREAD

**Issue by Epicycle23** [AllTheMods/atm6-sky#153]
After placing a chunky turtle in the end and exiting minecraft, the next time I loaded my world a crash occurred.
I had to disable advanced peripherals to get back into my world (the chunkly turtle was now a normal turtle).

**To Reproduce**
1. Place a chunky turtle in the end 
2. Exit the end (not sure if required)
3. Restart minecraft
4. Load the world

**Expected behavior**
The world  loads and the chunky turtle keeps the chunk loaded that it's on

**Crash log**
java.lang.NullPointerException: Exception in server tick loop
	at de.srendi.advancedperipherals.common.addons.computercraft.turtles.TurtleChunky.forceChunk(TurtleChunky.java:38) ~[?:0.4a] {re:classloading}
	at de.srendi.advancedperipherals.common.util.ChunkManager.lambda$validateTickets$0(ChunkManager.java:37) ~[?:0.4a] {re:classloading}
	at de.srendi.advancedperipherals.common.util.ChunkManager$$Lambda$32842/885968996.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[?:1.8.0_51] {}
	at de.srendi.advancedperipherals.common.util.ChunkManager.validateTickets(ChunkManager.java:30) ~[?:0.4a] {re:classloading}
	at net.minecraftforge.common.world.ForgeChunkManager.reinstatePersistentChunks(ForgeChunkManager.java:205) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:485) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:310) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:60) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$31436/486459987.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by Seniorendi** [comment]
Hey, I fixed that issue in 0.4b. If you want, you can update the mod to that version.
