### ISSUE TITLE
game crashes 

### ISSUE THREAD

**Issue by mqtq** [AllTheMods/atm6-sky#246]
08:15:16.813
Preparing crash report with UUID 4fd19543-9fbb-464b-b979-fe2de4a145b7
08:15:16.822
Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$32196/302000732.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.player.ServerPlayerEntity.func_70670_a(ServerPlayerEntity.java:1114)
	at net.minecraft.entity.LivingEntity.func_195064_c(LivingEntity.java:825)
	at com.thevortex.allthemodium.items.Allthemodium_Apple.func_77654_b(Allthemodium_Apple.java:33)
	at net.blay09.mods.excompressum.block.AutoSieveBaseBlock.func_225533_a_(AutoSieveBaseBlock.java:83)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640)
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338)
	at shadows.click.util.FakePlayerUtil.rightClickInDirection(FakePlayerUtil.java:157)
	at shadows.click.block.TileAutoClick.func_73660_a(TileAutoClick.java:76)
	at net.minecraft.world.World.func_217391_K(World.java:491)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	... 6 more
08:15:37.658

2021-04-12 08:15:16,929 Thread-5 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
08:15:37.659
Process crashed with exit code -1

**Comment by MelanX** [comment]
Give information. 
pack version, what did you do before the crash, a proper crash report via pastebin because what you did is aweful. Tell us things.
You don’t go to a doctor and say "I’m sick" and you want that the doctor finds out which kind of sickness.

**Comment by mqtq** [comment]
[crash-2021-04-12_08.15.16-server.txt](https://github.com/AllTheMods/atm6-sky/files/6295076/crash-2021-04-12_08.15.16-server.txt)
When I was placing bloks ("uniwersal cables" or "auto clicker" ) in compact machine then game crashed.
Pack version 1.0.6b

**Comment by bubel666** [comment]
Please help. any >1.15 pack crush code 0
Any <1.15 works normal

**Comment by MelanX** [comment]
And what about 1.15 packs?

> Please help. any >1.15 pack crush code 0
> Any <1.15 works normal

**Comment by mqtq** [comment]
> And what about 1.15 packs?
> 
> > Please help. any >1.15 pack crush code 0
> > Any <1.15 works normal

I will check it later because I found exacly which action caused problem.
I was caused when autoclecker used allthemodium apple (I hope it is correct name fo item) on sieve.

**Comment by MelanX** [comment]
It was just a joke, because you mentioned >1.15, <1.15 but not exactly 1.15 lol (but maybe my joke helps, would be even more funny for me)
