### ISSUE TITLE
[1.0.7] Nullptrexception on joining newly created server on the second time

### ISSUE THREAD

**Issue by Pthread-Create** [AllTheMods/atm6-sky#308]
`[02:19:10] [Render thread/INFO] [minecraft/ConnectingScreen]: Connecting to ****
[02:19:11] [Render thread/INFO] [Astral Sorcery/]: Built PerkTree with 417 perks!
[02:19:11] [Netty Client IO #16/INFO] [Silent Gear/]: Read 73 traits from server
[02:19:11] [Netty Client IO #16/INFO] [Silent Gear/]: Read 45 parts from server
[02:19:11] [Netty Client IO #16/INFO] [Silent Gear/]: Read 129 materials from server
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:magma not found.
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:hardened_clay not found.
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:quartz_ore not found.
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:log not found.
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:melon_block not found.
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:slime not found.
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:flowing_lava not found.
[02:19:29] [Netty Client IO #16/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:flowing_water not found.
[02:19:29] [Netty Client IO #16/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2919/1649998289@117aa606
java.lang.NullPointerException
	at com.darkere.crashutils.MemoryChecker.shutdown(MemoryChecker.java:33)
	at com.darkere.crashutils.MemoryChecker.restart(MemoryChecker.java:26)
	at com.darkere.crashutils.CrashUtils.configReload(CrashUtils.java:85)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:152)
	at java.util.Optional.ifPresent(Unknown Source)
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:152)
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$receiveSyncedConfig$5(ConfigTracker.java:123)
	at java.util.Optional.ifPresent(Unknown Source)
	at net.minecraftforge.fml.config.ConfigTracker.receiveSyncedConfig(ConfigTracker.java:121)
	at net.minecraftforge.fml.network.FMLHandshakeHandler.handleConfigSync(FMLHandshakeHandler.java:274)
	at net.minecraftforge.fml.util.ThreeConsumer.lambda$bindArgs$0(ThreeConsumer.java:43)
	at net.minecraftforge.fml.network.FMLHandshakeHandler.lambda$biConsumerFor$1(FMLHandshakeHandler.java:143)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128)
	at java.util.Optional.ifPresent(Unknown Source)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162)
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.NetworkInstance.dispatchLoginPacket(NetworkInstance.java:107)
	at net.minecraftforge.fml.network.FMLLoginWrapper.lambda$wrapperReceived$5(FMLLoginWrapper.java:69)
	at java.util.Optional.ifPresent(Unknown Source)
	at net.minecraftforge.fml.network.FMLLoginWrapper.wrapperReceived(FMLLoginWrapper.java:68)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90)
	at java.util.Optional.map(Unknown Source)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90)
	at net.minecraft.client.network.login.ClientLoginNetHandler.func_209521_a(ClientLoginNetHandler.java:147)
	at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:34)
	at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:11)
	at net.minecraft.network.NetworkManager.func_197664_a(NetworkManager.java:148)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:138)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Unknown Source)

` 
here's the error, how to reproduce it, create a server connect on it, disconnect and then reconnect on it and it nullptrexception.
happened to my friend too.

Server is running on windows.

**Comment by Pthread-Create** [comment]
reinstalling the client : allow you to reenter the server but if you disconnect and try again the nullptrexception kicks you again

**Comment by Pthread-Create** [comment]
here the logs when I reinstall the game :
`
[04:10:03] [Render thread/INFO] [minecraft/ConnectingScreen]: Connecting to ****
[04:10:04] [Render thread/INFO] [Astral Sorcery/]: Built PerkTree with 417 perks!
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/]: Read 73 traits from server
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/PartManager]: Registered part serializer 'silentgear:compound_part'
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/PartManager]: Registered part serializer 'silentgear:misc_upgrade'
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/]: Read 45 parts from server
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/MaterialManager]: Registered material serializer 'silentgear:standard'
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/MaterialManager]: Registered material serializer 'silentgear:compound'
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/MaterialManager]: Registered material serializer 'silentgear:custom_compound'
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/MaterialManager]: Registered material serializer 'silentgear:crafted'
[04:10:04] [Netty Client IO #0/INFO] [Silent Gear/]: Read 129 materials from server
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:magma not found.
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:hardened_clay not found.
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:quartz_ore not found.
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:log not found.
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:melon_block not found.
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:slime not found.
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:flowing_lava not found.
[04:10:23] [Netty Client IO #0/INFO] [STDOUT/]: [stepsword.mahoutsukai.tile.exchange.AlchemicalExchangeMahoujinTileEntity:addBlocksToList:250]: Mahou Tsukai Alchemical Exchange: Registry block minecraft:flowing_water not found.
[04:10:23] [Netty Client IO #0/INFO] [FluxNetworks/]: SERVER CONFIG LOADED
[04:10:23] [Netty Client IO #0/INFO] [wi.en.ModEngineersDecor/]: Config file changed engineersdecor-server.toml
[04:10:23] [Netty Client IO #0/INFO] [wi.en.ModEngineersTools/]: Config file changed engineerstools-server.toml
`
I think the error happens when [04:10:23] [Netty Client IO #0/INFO] [FluxNetworks/]: SERVER CONFIG LOADED

**Comment by Sythinia** [comment]
This same error is what i recieve on my server. after logging out the first time and trying to rejoin it kicks the player. Server restard seem to work for only joining again the first time after restart, second time same error apears again

**Comment by Deragonis** [comment]
removing crash utilities from the server is a minor fix, that was unavailable for me but removing it from the client as well did fix it fully for me

**Comment by Pdiddy973** [comment]
should be fixed in 1.0.8
