### ISSUE TITLE
PROTOCOL_ERROR on install

### ISSUE THREAD

**Issue by steve66** [AllTheMods/atm6-sky#324]
I am running the server installer and getting this error and can't seem to understand why.

[16:52:57] [INFO] [ 254/257] Downloaded mod: Botania-1.16.5-415.jar
[16:52:57] [INFO] [ 255/257] Downloaded mod: ClickMachine-1.16.4-4.3.0.jar
[16:52:57] [INFO] [ 256/257] Downloaded mod: reliquary-1.16.5-1.3.5.1096.jar
[16:52:57] [INFO] [ 257/257] Downloaded mod: valhelsia_core-16.0.6.jar
[16:52:58] [INFO] Attempting to download installer from http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.1.2/forge-1.16.5-36.1.2-installer.jar
[16:52:58] [ERROR] Problem while installing Loader

okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
	at okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:153)
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:125)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at atm.bloodworkxgaming.serverstarter.In

**Comment by oly2o6** [comment]
appears to be a small amount of people having issues with server starter, if this is still happening use the client files and remove ding and packmenu, should work the same
