### ISSUE TITLE
Update from 1.0.6 to 1.0.8

### ISSUE THREAD

**Issue by deevee1982** [AllTheMods/atm6-sky#331]
root@mc-MS-7823:~/ATM6S# ./startserver.sh
Skipping download. Using existing serverstarter-2.0.1.jar
[13:06:01] [ERROR] Failed to load Yaml

Cannot create property=forgeInstalled for JavaBean=LockFile(loaderInstalled=false, packInstalled=false, loaderVersion=NONE, mcVersion=NONE, packUrl=NONE, spongeBootstrapper=NONE)
 in 'reader', line 2, column 1:
    {forgeInstalled: true, forgeVers ...
    ^
Unable to find property 'forgeInstalled' on class: atm.bloodworkxgaming.serverstarter.config.LockFile
 in 'reader', line 2, column 18:
    {forgeInstalled: true, forgeVersion: 36.0.46, mcV ...
                     ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:270)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
        at atm.bloodworkxgaming.serverstarter.ServerStarter$Companion.readLockFile(ServerStarter.kt:89)
        at atm.bloodworkxgaming.serverstarter.ServerStarter$Companion.access$readLockFile(ServerStarter.kt:24)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.<clinit>(ServerStarter.kt:40)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:200)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'forgeInstalled' on class: atm.bloodworkxgaming.serverstarter.config.LockFile
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:159)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:148)
        at org.yaml.snakeyaml.TypeDescription.discoverProperty(TypeDescription.java:246)
        at org.yaml.snakeyaml.TypeDescription.getProperty(TypeDescription.java:257)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:209)
        ... 12 more
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class atm.bloodworkxgaming.serverstarter.ServerStarter
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:208)
root@mc-MS-7823:~/ATM6S#

**Comment by oly2o6** [comment]
appears to be a small amount of people having issues with server starter, if this is still happening use the client files and remove ding and packmenu, should work the same
