### ISSUE TITLE
Using the Fluid Sieving Machine to make Biotite Dust causes the game to crash

### ISSUE THREAD

**Issue by rolsch8026** [AllTheMods/atm6-sky#412]
**Describe the bug**
When using the Fluid Sieving Machine to make Biotite Dust. It causes the game to crash.

**To Reproduce**
1. Left Click on Fluid Sieving Machine with a bucket of Fermented Ore Meat (Biotite Ore).
2. Right Click on Fluid Sieving Machine.
3. Shift + Left Click a stack of Sand.

**Expected behavior**
 I except to make Biotite Dust.

**Additional context**
Java Edition
Modpack Version: 1.16.5
Updated: May 28, 2021
MD5: 267f1f6b75f3c366dc8b7ee68cf9a41c
Crash Log: [10:12:40] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID f73203fb-cbec-4ddc-8279-741a352adde8
[10:12:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
Caused by: java.lang.NullPointerException
	at com.hrznstudio.titanium.util.TagUtil.getItemWithPreference(TagUtil.java:95) ~[titanium:3.2.8.2] {re:classloading}
	at com.buuz135.industrial.fluid.OreTitaniumFluidAttributes.getOutputDust(OreTitaniumFluidAttributes.java:81) ~[industrialforegoing:3.2.11] {re:classloading}
	at com.buuz135.industrial.block.resourceproduction.tile.FluidSievingMachineTile.canIncrease(FluidSievingMachineTile.java:70) ~[industrialforegoing:3.2.11] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialProcessingTile.lambda$new$2(IndustrialProcessingTile.java:78) ~[industrialforegoing:3.2.11] {re:classloading}
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:36) ~[titanium:3.2.8.2] {re:classloading}
	at com.hrznstudio.titanium.block.tile.ActiveTile.func_73660_a(ActiveTile.java:222) ~[titanium:3.2.8.2] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:create.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	... 5 more
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by oly2o6** [comment]
should be reported to the mod devs
