### ISSUE TITLE
Fresh Server will not start ATM6 1.16.13

### ISSUE THREAD

**Issue by Elcar903** [AllTheMods/atm6-sky#480]
Here is the error I get, I cant seem to get pasted it.
I did have this issue on ATM6 1.16.2

here is the Server log 

[17:16:33] [INFO] Done installing loader, deleting installer!
[17:16:47] [INFO] Starting to installing Additional Files
[17:16:47] [INFO] Starting to copy local files.
[17:16:47] [INFO] Starting Loader, output incoming
2021-06-28 17:16:49,506 main WARN Advanced terminal features are not available in this environment
[17:16:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.31, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[17:16:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16.0.1 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x4de5031f) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x4de5031f
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

**Comment by TheRanker** [comment]
Your using java 16. Which is only supported in Minecraft 1.17 versions. For anything 1.16.5 or below use java 11 or java 8

**Comment by Elcar903** [comment]
which is better Java 8 or Java 11 for ATM 6

**Comment by TheRanker** [comment]
Java11 recommended for atm6

**Comment by Elcar903** [comment]
ok thank you
