### ISSUE TITLE
Using New version with drill mod removed server still crashes

### ISSUE THREAD

**Issue by ModernGamingWorld** [AllTheMods/atm6-sky#55]
[20.03 23:05:10] [Server] [main/WARN] [minecraft/Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
[20.03 23:05:10] [Server] java.util.concurrent.ExecutionExceptionjava.lang.IllegalStateException: Missing required tags: minecraft:fluid:minecraft:water
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at net.minecraft.server.Main.main(Main.java:130) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
[20.03 23:05:10] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[custom.jar:36.{}
[20.03 23:05:10] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
[20.03 23:05:10] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
[20.03 23:05:10] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
[20.03 23:05:10] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
[20.03 23:05:10] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
[20.03 23:05:10] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [custom.jar:?] {}
[20.03 23:05:10] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [custom.jar:?] {}
[20.03 23:05:10] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [custom.jar:?] {}
[20.03 23:05:10] [Server] Caused byjava.lang.IllegalStateException: Missing required tags: minecraft:fluid:minecraft:water
[20.03 23:05:10] [Server] 	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:47) ~[?:?] {re:classloading,pl:accesstransformer:B}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
[20.03 23:05:10] [Server] 	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?] {re:classloading}
[20.03 23:05:10] [Server] 	at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?] {re:classloading}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_{}
[20.03 23:05:10] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_{re:computing_frames}
[20.03 23:05:10] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_{}
[20.03 23:05:11] [Multicraft] Server shut down (starting)

**Comment by OmegaAlpha83** [comment]
I submitted a bug report too because I can't even update or download the mod pack anymore it just gave this error 
![image](https://user-images.githubusercontent.com/81062066/111893694-d0916f00-89da-11eb-959c-4c3f045a9884.png)
 tried to update my already installed profile to the update where they remove multi drills and now I can't even download or update the mod pack :/

**Comment by WhitePhant0m** [comment]
Update your pack, later versions fix this.
