### ISSUE TITLE
World data not being saved

### ISSUE THREAD

**Issue by KazKazath** [AllTheMods/atm6-sky#61]
World data does not get regularly updated and results in whole chunks being rolled back when reloaded. This occurs in any dimension including the overworld.

When I load my server an error message occurs with chunks. I have no idea if this is caused by this bug, but I do know there is a correlation with this and this new version. The error message is as follows:

[17:33:17] [Server thread/ERROR] [minecraft/ChunkManager]: Failed to save chunk [-125, -133]
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:388) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:morered.mixins.json:ChunkManagerMixin,pl:mixin:APP:ftbchunks.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:366) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:morered.mixins.json:ChunkManagerMixin,pl:mixin:APP:ftbchunks.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:323) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.NullPointerException
	at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180) ~[appliedenergistics2:8.3.0-alpha.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleSave$10(ChunkManager.java:403) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:morered.mixins.json:ChunkManagerMixin,pl:mixin:APP:ftbchunks.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}

It is expected that world data is saved so that edits made to the world is kept when loading and reloading chunks. Because chunks don't want to save world data it rolls back, and voids any and all changes meaning blocks can be duped/deleted. This includes your tombstone which means if you died far away enough from your spawn to unload the chunk, when you get back it'd have rolled back to before you died voiding all your belongings.

For now I have rolled back to 1.0.2 and hope to see this problem addressed.

**Comment by Mordaii** [comment]
I am running a different pack, but I had this same problem with Garden of Glass in an AE2 Meteorite zone.    I had to remove AE2 and the supporting mods that go along with it to get my server to save properly again.

**Comment by WhitePhant0m** [comment]
Update to 1.0.4b, that has an older version of AE2 that doesn't bug out like this.
